#database configuration
server:
  port: 7071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_db
    username: root
    password: 'abhinav1#'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true